name: Docker QGIS server CI

on:
  push:
  pull_request:

defaults:
  run:
    shell: bash

jobs:

  make-docker-images:
    name: Build docker image for 3.16
    runs-on: ubuntu-20.04
    env:
      VERSION: 3.16

    steps:

    - name: Set up QEMU for amd64 and arm64
      uses: docker/setup-qemu-action@27d0a4f181a40b142cce983c5393082c365d1480  # v1.2.0 (2021-10-22)
      with:
        platforms: linux/amd64,linux/arm64

    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@94ab11c41e45d028884a99163086648e898eed25  # v1.6.0 (2021-10-22)

    - name: Docker meta
      id: meta
      uses: docker/metadata-action@3a3bb3a81753dc99f090d24ee7e5343838b73a96  # v3.5.0 (2021-10-22)
      with:
        images: sogis/qgis-server-base
        labels: |
          org.opencontainers.image.title=qgis-server-base
          org.opencontainers.image.version=${{ env.VERSION }}
          org.opencontainers.image.base.name=phusion/baseimage:focal-1.1.0
        tags: |
          type=raw,value=${{ env.VERSION }},enable=true,priority=200

    - name: Login to GitHub Container Registry
      uses: docker/login-action@f054a8b539a109f9f41c372932f1ae047eff08c9  # v1.10.0 (2021-10-22)
      with:
        username: ${{ secrets.DOCKERHUB_USERNAME }}
        password: ${{ secrets.DOCKERHUB_TOKEN }}
      if: ${{ (github.ref == 'refs/heads/main') && (github.event_name != 'pull_request') && !env.ACT }}

    - name: Multi-platform build and push
      uses: docker/build-push-action@a66e35b9cbcf4ad0ea91ffcaf7bbad63ad9e0229  # v2.7.0 (2021-10-22)
      with:
        platforms: linux/amd64,linux/arm64
        #context: github.com/postgis/docker-postgis#master
        #file: Dockerfile
        tags: ${{ steps.meta.outputs.tags }}
        labels: ${{ steps.meta.outputs.labels }}
        pull: false
        push: ${{ (github.ref == 'refs/heads/main') && (github.event_name != 'pull_request') && !env.ACT }}